services:
  - type: web
    name: ewallet-core-backend
    runtime: php
    plan: free
    region: frankfurt
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_NAME
        value: "Wafi E-Wallet"
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: MAIL_MAILER
        value: log
